CREATE TABLE [dbo].[USER]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UserName] VARCHAR(50) NOT NULL,
    [CreatedDate] DATETIME2 NULL DEFAULT GETUTCDATE(), 
    CONSTRAINT [AK_USER_USERNAME] UNIQUE ([UserName]) 
)
